services:
    app_php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: crm-app
        volumes:
            - ./:/var/www/html
            - ./storage:/var/www/html/storage
            - ./logs:/var/www/html/storage/logs
        networks:
            - laravel
        depends_on:
            - mysql
#            - redis
        #      - meilisearch
#        restart: unless-stopped

    nginx:
        image: nginx:stable
        container_name: crm-nginx
        ports:
            - "${FORWARD_WEB_PORT:-80}:80"
        volumes:
            - ./:/var/www/html
            - ./storage:/var/www/html/storage
            - ./logs:/var/www/html/storage/logs
        depends_on:
            - app_php
        networks:
            - laravel
        restart: unless-stopped

    mysql:
        image: mysql:8.0
        container_name: crm-mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        restart: unless-stopped

#    redis:
#        image: redis:alpine
#        container_name: crm-redis
#        volumes:
#            - redis_data:/data
#        networks:
#            - laravel
#        restart: unless-stopped
    #  meilisearch:
    #    image: getmeili/meilisearch:v1.11
    #    container_name: laravel-meilisearch
    #    environment:
    #      MEILI_NO_ANALYTICS: "true"
    #    volumes:
    #      - meilidata:/meili_data
    #    networks:
    #      - laravel

    #  node:
    #    image: node:20-alpine
    #    container_name: laravel-node
    #    working_dir: /var/www/html
    #    volumes:
    #      - ./:/var/www/html
    #    command: sh -c "npm install"
    #    networks:
    #      - laravel

#    horizon:
#        build:
#            context: .
#            dockerfile: docker/php/Dockerfile
#        container_name: crm-horizon
#        volumes:
#            - ./:/var/www/html
#            - ./docker/horizon/supervisord.conf:/etc/supervisord.conf
#            - ./docker/horizon/horizon.conf:/etc/supervisor/conf.d/horizon.conf
#        command: /usr/bin/supervisord -c /etc/supervisord.conf
#        depends_on:
#            - redis
#            - mysql
#        networks:
#            - laravel
#        restart: unless-stopped

volumes:
    dbdata:
#    meilidata:
#    redis_data:

networks:
    laravel:
        driver: bridge
