<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Scheduled Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }

        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            color: #2c3e50;
        }

        .content {
            background-color: #ffffff;
            padding: 20px;
            border: 1px solid #dee2e6;
            border-radius: 5px;
        }

        .info-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        .info-table th,
        .info-table td {
            padding: 10px;
            text-align: left;
            border-bottom: 1px solid #dee2e6;
        }

        .info-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }

        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            font-size: 12px;
            color: #6c757d;
        }

        .attachment-info {
            background-color: #e9ecef;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $report->name }}</h1>
        <p>Scheduled Report Delivery</p>
    </div>

    <div class="content">
        <p>Hello,</p>

        <p>Your scheduled report <strong>{{ $report->name }}</strong> has been generated and is ready for download.</p>

        <table class="info-table">
            <tr>
                <th>Report Name:</th>
                <td>{{ $report->name }}</td>
            </tr>
            <tr>
                <th>Description:</th>
                <td>{{ $report->description ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>Report Type:</th>
                <td>{{ ucwords(str_replace('_', ' ', $report->report_type)) }}</td>
            </tr>
            <tr>
                <th>Generated On:</th>
                <td>{{ $generatedAt }}</td>
            </tr>
            <tr>
                <th>Records Processed:</th>
                <td>{{ number_format($execution->records_processed ?? 0) }}</td>
            </tr>
            <tr>
                <th>Execution Time:</th>
                <td>{{ $execution->execution_time ?? 0 }} seconds</td>
            </tr>
        </table>

        <div class="attachment-info">
            <h3>📎 Report Attachment</h3>
            <p>The report has been generated as <strong>{{ $fileName }}</strong> and is attached to this email.</p>
            <p>You can download and open the file using your preferred application.</p>
        </div>

        @if($report->description)
        <div style="margin-top: 20px;">
            <h3>Report Details:</h3>
            <p>{{ $report->description }}</p>
        </div>
        @endif

        <p>If you have any questions about this report, please contact your system administrator.</p>

        <p>Best regards,<br>
            CRM System</p>
    </div>

    <div class="footer">
        <p>This is an automated email generated by the CRM system.</p>
        <p>Report ID: {{ $report->id }} | Execution ID: {{ $execution->id }}</p>
    </div>
</body>

</html>